ALTER TABLE RegisteredUser ADD CONSTRAINT
  UN_RegisteredUser_UserLogin UNIQUE(UserLogin);
ALTER TABLE SshKey ADD CONSTRAINT FK_SshKey_UserId
  FOREIGN KEY (SshOwner) REFERENCES RegisteredUser(UserId) ON DELETE CASCADE;
ALTER TABLE GpgKey ADD CONSTRAINT FK_GpgKey_UserId
  FOREIGN KEY (GpgOwner) REFERENCES RegisteredUser(UserId) ON DELETE CASCADE;
ALTER TABLE Package ADD CONSTRAINT FK_Author_UserId
  FOREIGN KEY (Author) REFERENCES RegisteredUser(UserId) ON DELETE CASCADE;
ALTER TABLE Package ADD CONSTRAINT FK_LastVersion_VersionId
  FOREIGN KEY (LastVersion) REFERENCES Version(VersionId) ON DELETE CASCADE;
ALTER TABLE Version ADD CONSTRAINT FK_VPackage_PackageId
  FOREIGN KEY (VPackage) REFERENCES Package(PackageId) ON DELETE CASCADE;
