INSERT INTO Package VALUES
    (1, 'egison','http://hagi.is.s.u-tokyo.ac.jp/~egi/egison/','MIT','Satoshi Egi',5, False, True, False, False),
    (2, 'timeplot','http://haskell.org/haskellwiki/Timeplot','BSD3','Eugene Kirpichov <ekirpichov@gmail.com>',10, True, True, False, False),
    (3, 'sbv','http://leventerkok.github.com/sbv/','BSD3','Levent Erkok',11, True, True, False, False),
    (4, 'HTTP','http://www.haskell.org/http/','BSD3','Warrick Gray <warrick.gray@hotmail.com>',16, True, True, False, False),
    (5, 'conduit','http://github.com/snoyberg/conduit','BSD3','Michael Snoyman',21, True, True, False, False),
    (6, 'hledger-web','http://hledger.org','GPL','Simon Michael <simon@joyful.com>',26, True, True, False, False),
    (7, 'resourcet','http://github.com/snoyberg/conduit','BSD3','Michael Snoyman',31, True, True, False, False),
    (8, 'shakespeare','http://www.yesodweb.com/book/templates','BSD3','Michael Snoyman <michael@snoyman.com>',36, False, True, False, False),
    (9, 'relational-query','http://twitter.com/khibino','BSD3','Kei Hibino',41, True, True, False, False),
    (10, 'hledger','http://hledger.org','GPL','Simon Michael <simon@joyful.com>',46, True, False, False, False),
    (11, 'lens','http://github.com/ekmett/lens/','BSD3','Edward A. Kmett',51, True, True, False, False),
    (12, 'containers','','BSD3','',56, True, False, False, False),
    (13, 'scientific','https://github.com/basvandijk/scientific','BSD3','Bas van Dijk',61, True, True, False, False),
    (14, 'cblrepo','','OtherLicense','Magnus Therning',66, True, True, False, False),
    (15, 'aeson','http://github.com/mailrank/aeson','BSD3','Bryan OSullivan <bos@mailrank.com>',71, True, False, False, False),
    (16, 'semigroupoids','http://github.com/ekmett/semigroupoids','BSD3','Edward A. Kmett',76, False, True, False, False),
    (17, 'persistent-template','http://www.yesodweb.com/book/persistent','BSD3','Michael Snoyman <michael@snoyman.com>',81, True, True, False, False),
    (18, 'text','','BSD3','Tom Harper <rtharper@aftereternity.co.uk>',86, True, True, False, False),
    (19, 'http-client','https://github.com/snoyberg/http-client','MIT','Michael Snoyman',91, True, True, False, False),
    (20, 'Cabal','http://www.haskell.org/cabal/','BSD3','Isaac Jones <ijones@syntaxpolice.org>',96, True, True, False, False),
    (21, 'base','','BSD3','',101, True, True, False, False),
    (22, 'haskell-src-meta','','BSD3','Matt Morrow',106, True, True, False, False),
    (23, 'scotty','https://github.com/scotty-web/scotty','BSD3','Andrew Farmer <afarmer@ittc.ku.edu>',111, True, True, False, False),
    (24, 'diagrams-contrib','http://projects.haskell.org/diagrams/','BSD3','Various',116, False, True, False, False),
    (25, 'pandoc','http://sophos.berkeley.edu/macfarlane/pandoc','GPL','John MacFarlane <jgm@berkeley.edu>',121, True, True, False, False),
    (26, 'wai-routes','https://github.com/ajnsit/wai-routes','MIT','Anupam Jain',126, True, True, False, False),
    (27, 'cuda','','BSD3','Trevor L. McDonell <tmcdonell@cse.unsw.edu.au>',131, True, True, False, False),
    (28, 'type-natural','https://github.com/konn/type-natural','BSD3','Hiromi ISHII',136, True, True, False, False),
    (29, 'cabal-install','','BSD3','Lemmih <lemmih@gmail.com>
Paolo Martini <paolo@nemail.it>
Bjorn Bringert <bjorn@bringert.net>
Isaac Potoczny-Jones <ijones@syntaxpolice.org>
Duncan Coutts <duncan@haskell.org>',141, True, True, False, False),
    (30, 'attoparsec','','BSD3','Bryan OSullivan <bos@serpentine.com>',146, True, True, False, False),
    (31, 'either','http://github.com/ekmett/either/','BSD3','Edward A. Kmett',151, True, True, False, False),
    (32, 'pontarius-xmpp','http://www.pontarius.org/','LGPL','Jon Kristensen, Mahdi Abdinejadi',156, True, False, False, False),
    (33, 'hlint','http://community.haskell.org/~ndm/hlint/','GPL','Neil Mitchell <ndmitchell@gmail.com>',161, True, True, False, False),
    (34, 'git-annex','http://git-annex.branchable.com/','GPL','Joey Hess',166, True, True, False, False),
    (35, 'binary','http://code.haskell.org/binary/','BSD3','Lennart Kolmodin <kolmodin@dtek.chalmers.se>',171, True, True, False, False),
    (36, 'protocol-buffers','http://hackage.haskell.org/cgi-bin/hackage-scripts/package/protocol-buffers','BSD3','Christopher Edward Kuklewicz',176, True, True, False, False),
    (37, 'warp','http://github.com/snoyberg/warp','BSD3','Michael Snoyman, Matt Brown',181, True, True, False, False),
    (38, 'network','','BSD3','',186, True, True, False, False),
    (39, 'purescript','','MIT','Phil Freeman <paf31@cantab.net>',191, True, True, False, False),
    (40, 'rainbow','http://github.com/massysett/rainbow','BSD3','Omari Norman',196, True, True, False, False),
    (41, 'uhc-util','https://github.com/UU-ComputerScience/uhc-utils','BSD3','Atze Dijkstra',201, True, True, False, False),
    (42, 'github','https://github.com/mike-burns/github','BSD3','Mike Burns',206, True, True, False, False),
    (43, 'ncurses','http://john-millikin.com/software/bindings/ncurses/','GPL','John Millikin <jmillikin@gmail.com>',211, True, True, False, False),
    (44, 'tls','http://github.com/vincenthz/hs-tls','BSD3','Vincent Hanquez <vincent@snarc.org>',216, True, True, False, False),
    (45, 'yaml','http://github.com/snoyberg/yaml/tree/master','BSD3','Michael Snoyman <michael@snoyman.com>',221, True, True, False, False),
    (46, 'preamble','https://github.com/swift-nav/preamble','MIT','Swift Navigation Inc.',226, True, True, False, False),
    (47, 'persistent-sqlite','http://docs.yesodweb.com/persistent/','BSD3','Michael Snoyman <michael@snoyman.com>',231, True, True, False, False),
    (48, 'safecopy','http://acid-state.seize.it/safecopy','PublicDomain','David Himmelstrup',236, True, True, False, False),
    (49, 'haskell-src-exts','http://code.haskell.org/HSP/haskell-src-exts','BSD3','Niklas Broberg',241, True, True, False, False),
    (50, 'time','http://semantic.org/TimeLib/','BSD3','Ashley Yakeley',246, True, False, False, False),
    (51, 'QuickCheck','http://www.haskell.org/QuickCheck/','BSD3','Koen Claessen <koen@cs.chalmers.se>',251, True, True, False, False),
    (52, 'rethinkdb','http://github.com/atnnn/haskell-rethinkdb','Apache','Etienne Laurin',256, True, True, False, False),
    (53, 'repa-io','http://repa.ouroborus.net','BSD3','The DPH Team',261, True, True, False, False),
    (54, 'snaplet-fay','https://github.com/bergmark/snaplet-fay','BSD3','Adam Bergmark',266, True, True, False, False),
    (55, 'bamboo','http://github.com/nfjinjing/bamboo/tree/master','GPL','Wang, Jinjing',271, True, True, False, False),
    (56, 'uhc-light','https://github.com/UU-ComputerScience/uhc','BSD3','Atze Dijkstra',276, True, True, False, False),
    (57, 'hoogle','http://www.haskell.org/hoogle/','GPL','Neil Mitchell <ndmitchell@gmail.com>',281, True, True, False, False),
    (58, 'constraints','http://github.com/ekmett/constraints/','BSD3','Edward A. Kmett',286, True, True, False, False),
    (59, 'shake','http://community.haskell.org/~ndm/shake/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',291, True, True, False, False),
    (60, 'shellmate','http://github.com/valderman/shellmate','BSD3','Anton Ekblad',296, True, True, False, False),
    (61, 'HDBC-mysql','http://www.maubi.net/~waterson/hacks/hdbc-mysql.html','LGPL','Chris Waterson',301, True, True, False, False),
    (62, 'fltkhs','http://github.com/deech/fltkhs','MIT','Aditya Siram',306, True, True, False, False),
    (63, 'repa-algorithms','http://repa.ouroborus.net','BSD3','The DPH Team',311, True, True, False, False),
    (64, 'hspec','http://hspec.github.io/','MIT','',316, True, True, False, False),
    (65, 'protocol-buffers-descriptor','http://hackage.haskell.org/cgi-bin/hackage-scripts/package/protocol-buffers','BSD3','Christopher Edward Kuklewicz',321, True, True, False, False),
    (66, 'semigroups','http://comonad.com/reader/','BSD3','Edward A. Kmett',326, True, True, False, False),
    (67, 'threepenny-gui','http://github.com/HeinrichApfelmus/threepenny-gui','BSD3','Chris Done, Heinrich Apfelmus',331, False, True, False, False),
    (68, 'secp256k1','http://github.com/haskoin/secp256k1#readme','PublicDomain','Jean-Pierre Rupp',336, True, True, False, True),
    (69, 'friday','https://github.com/RaphaelJ/friday','LGPL','Raphael Javaux <raphaeljavaux[at]gmail.com>',341, True, True, False, False),
    (70, 'persistent-postgresql','http://docs.yesodweb.com/persistent/','BSD3','Michael Snoyman <michael@snoyman.com>',346, False, True, False, False),
    (71, 'rethinkdb-client-driver','https://github.com/wereHamster/rethinkdb-client-driver','MIT','Tomas Carnecky',351, True, True, False, False),
    (72, 'streaming-bytestring','https://github.com/michaelt/streaming-bytestring','BSD3','michaelt',356, True, True, False, False),
    (73, 'highlighting-kate','http://johnmacfarlane.net/highlighting-kate','GPL','John MacFarlane',361, True, True, False, False),
    (74, 'RSA','','BSD3','Adam Wick <awick@galois.com>',366, True, True, False, False),
    (75, 'haskell-docs','http://github.com/chrisdone/haskell-docs','BSD3','Chris Done',371, True, True, False, False),
    (76, 'persistent','http://docs.yesodweb.com/persistent/','BSD3','Michael Snoyman <michael@snoyman.com>',376, True, True, False, False),
    (77, 'random-fu','http://code.haskell.org/~mokus/random-fu','PublicDomain','James Cook <james.cook@usma.edu>',381, False, True, False, True),
    (78, 'vector','http://darcs.haskell.org/vector','BSD3','Roman Leshchinskiy <rl@cse.unsw.edu.au>',386, True, True, False, False),
    (79, 'shakers','https://github.com/swift-nav/shakers','MIT','Swift Navigation Inc.',391, True, True, False, False),
    (80, 'yaml-light-lens','','BSD3','Anthony Cowley',396, True, True, False, False),
    (81, 'sandi','http://hackage.haskell.org/package/sandi','BSD3','Magnus Therning',401, True, True, False, False),
    (82, 'yesod','http://docs.yesodweb.com/yesod/','BSD3','Michael Snoyman <michael@snoyman.com>',406, True, True, False, False),
    (83, 'conduit-extra','http://github.com/snoyberg/conduit','MIT','Michael Snoyman',411, False, True, False, False),
    (84, 'http-conduit','http://www.yesodweb.com/book/http-conduit','BSD3','Michael Snoyman <michael@snoyman.com>',416, True, True, False, False),
    (85, 'directory','','BSD3','',421, True, True, False, False),
    (86, 'gl','','BSD3','Edward A. Kmett, GabrÃ­el ArthÃºr PÃ©tursson, Sven Panne',426, True, True, False, False),
    (87, 'hakyll','http://jaspervdj.be/hakyll','BSD3','Jasper Van der Jeugt',431, True, True, False, False),
    (88, 'hint','','BSD3','Daniel Gorin',436, False, True, False, False),
    (89, 'simple-effects','https://gitlab.com/LukaHorvat/simple-effects','BSD3','Luka Horvat',441, True, True, False, False),
    (90, 'OpenGLRaw','http://www.haskell.org/haskellwiki/Opengl','BSD3','',446, True, True, False, False),
    (91, 'blaze-html','http://jaspervdj.be/blaze','BSD3','Jasper Van der Jeugt, Simon Meier',451, True, True, False, False),
    (92, 'computational-algebra','https://github.com/konn/computational-algebra','BSD3','Hiromi ISHII',456, True, True, False, False),
    (93, 'hmatrix','http://alberrto.googlepages.com/gslhaskell','GPL','Alberto Ruiz',461, True, False, False, False),
    (94, 'pointfree','','OtherLicense','Thomas JÃ¤ger',466, True, True, False, False),
    (95, 'unordered-containers','','BSD3','Johan Tibell <johan.tibell@gmail.com>',471, True, True, False, False),
    (96, 'cabal2nix','http://github.com/peti/cabal2nix','BSD3','Peter Simons <simons@cryp.to>',476, True, True, False, False),
    (97, 'wai','http://github.com/snoyberg/wai','BSD3','Michael Snoyman',481, True, True, False, False),
    (98, 'distributive','http://github.com/ekmett/distributive/','BSD3','Edward A. Kmett',486, True, True, False, False),
    (99, 'rest-client','','BSD3','',491, True, True, False, False),
    (100, 'rest-happstack','','BSD3','',496, True, True, False, False),
    (101, 'YamlReference','www.ben-kiki.org/oren/YamlReference','LGPL','Oren Ben-Kiki',501, True, True, False, False),
    (102, 'sdl2','','BSD3','GabrÃ­el ArthÃºr PÃ©tursson',506, True, True, False, False),
    (103, 'yesod-core','http://www.yesodweb.com/','BSD3','Michael Snoyman <michael@snoyman.com>',511, True, True, False, False),
    (104, 'zlib','','BSD3','Duncan Coutts <duncan@haskell.org>',516, True, True, False, False),
    (105, 'haskeline','http://trac.haskell.org/haskeline','BSD3','Judah Jacobson',521, True, True, False, False),
    (106, 'texmath','http://github.com/jgm/texmath','GPL','John MacFarlane',526, True, True, True, False),
    (107, 'Unique','','BSD3','Volodymyr Yaschenko',531, True, True, False, False),
    (108, 'legion','https://github.com/owensmurray/legion','Apache','Rick Owens',536, True, True, False, False),
    (109, 'rainbox','http://www.github.com/massysett/rainbox','BSD3','Omari Norman',541, True, True, False, False),
    (110, 'damnpacket','','MIT','Jude Taylor',545, True, True, False, False),
    (111, 'quickcheck-instances','https://github.com/aslatter/qc-instances','BSD3','Antoine Latter',550, True, True, False, False),
    (112, 'wolf','https://github.com/swift-nav/wolf','MIT','Swift Navigation Inc.',555, True, True, False, False),
    (113, 'criterion','','BSD3','Bryan OSullivan <bos@serpentine.com>',560, True, True, False, False),
    (114, 'cryptonite','https://github.com/vincenthz/cryptonite','BSD3','Vincent Hanquez <vincent@snarc.org>',565, True, True, False, False),
    (115, 'transformers','','BSD3','Andy Gill',570, True, True, False, False),
    (116, 'wai-extra','http://github.com/snoyberg/wai-extra','BSD3','Michael Snoyman',575, True, False, False, False),
    (117, 'OpenGL','http://www.haskell.org/HOpenGL/','BSD3','',580, True, True, False, False),
    (118, 'Win32','','BSD3','Alastair Reid',585, True, True, False, False),
    (119, 'darcs','http://darcs.net/','GPL','David Roundy <droundy@darcs.net>, <darcs-users@darcs.net>',590, True, True, False, False),
    (120, 'heckle','https://github.com/2016rshah/heckle','MIT','Rushi Shah',595, True, True, False, False),
    (121, 'lzma-conduit','http://github.com/alphaHeavy/lzma-conduit','BSD3','Nathan Howell <nhowell@alphaheavy.com>',600, True, False, False, False),
    (122, 'yesod-bin','http://www.yesodweb.com/','MIT','Michael Snoyman <michael@snoyman.com>',605, True, True, False, False),
    (123, 'cabal-rpm','http://www.serpentine.com/software/cabal-rpm/','GPL','Bryan OSullivan <bos@serpentine.com>',610, True, True, False, False),
    (124, 'llvm-general','','BSD3','Benjamin S.Scarlet <fgthb0@greynode.net>',615, True, True, False, False),
    (125, 'pureMD5','','BSD3','Thomas DuBuisson <thomas.dubuisson@gmail.com>',620, True, True, False, False),
    (126, 'purescript-bridge','','AGPL','Robert Klotzner',625, True, True, True, False),
    (127, 'sendfile','http://patch-tag.com/r/sendfile','BSD3','Matthew Elder <matt@mattelder.org>',630, True, True, False, False),
    (128, 'ghc-mod','http://www.mew.org/~kazu/proj/ghc-mod/','BSD3','Kazu Yamamoto <kazu@iij.ad.jp>
Daniel GrÃ¶ber <dxld@darkboxed.org>
Alejandro Serrano <trupill@gmail.com>',635, True, True, False, False),
    (129, 'machinecell','http://github.com/as-capabl/machinecell','BSD3','Hidenori Azuma',640, True, True, False, False),
    (130, 'lentil','http://www.ariis.it/static/articles/lentil/page.html','GPL','Francesco Ariis <fa-ml@ariis.it>',645, True, True, False, False),
    (131, 'pipes','','BSD3','Gabriel Gonzalez',650, True, True, False, False),
    (132, 'postgresql-libpq','http://github.com/lpsmith/postgresql-libpq','BSD3','Grant Monroe, Leon P Smith',655, True, True, False, False),
    (133, 'shelly','https://github.com/yesodweb/Shelly.hs','BSD3','Greg Weber, Petr Rockai',660, False, True, False, False),
    (134, 'crypto-enigma','https://github.com/orome/crypto-enigma-hs','BSD3','Roy Levien',662, True, True, False, False),
    (135, 'liquid-fixpoint','https://github.com/ucsd-progsys/liquid-fixpoint','BSD3','Ranjit Jhala, Niki Vazou, Eric Seidel',667, True, True, False, False),
    (136, 'pandoc-citeproc','','BSD3','John MacFarlane, Andrea Rossato',672, True, True, False, False),
    (137, 'rest-snap','','BSD3','',677, True, True, False, False),
    (138, 'time-exts','https://github.com/enzoh/time-exts','BSD3','Enzo Haussecker <ehaussecker@gmail.com>',682, True, True, False, False),
    (139, 'HUnit','http://hunit.sourceforge.net/','BSD3','Dean Herington',687, True, True, False, False),
    (140, 'extra','https://github.com/ndmitchell/extra#readme','BSD3','Neil Mitchell <ndmitchell@gmail.com>',692, True, True, False, False),
    (141, 'hashable','http://github.com/tibbe/hashable','BSD3','Milan Straka <fox@ucw.cz>
Johan Tibell <johan.tibell@gmail.com>',697, True, True, False, False),
    (142, 'irc-core','https://github.com/glguy/irc-core','BSD3','Eric Mertens',702, True, True, False, False),
    (143, 'phoityne-vscode','https://sites.google.com/site/phoityne/vscode','BSD3','phoityne_hs',707, True, True, False, False),
    (144, 'pretty-show','http://wiki.github.com/yav/pretty-show','BSD3','Iavor S. Diatchki',712, True, True, False, False),
    (145, 'web3','https://github.com/airalab/hs-web3#readme','BSD3','Alexander Krupenkin',717, True, True, False, False),
    (146, 'alex','http://www.haskell.org/alex/','BSD3','Chris Dornan and Simon Marlow',722, True, True, False, False),
    (147, 'http-api-data','http://github.com/fizruk/http-api-data','BSD3','Nickolay Kudasov <nickolay.kudasov@gmail.com>',727, True, True, False, False),
    (148, 'streaming-commons','https://github.com/fpco/streaming-commons','MIT','Michael Snoyman, Gabriel Gonzalez',732, True, True, False, False),
    (149, 'case-insensitive','','BSD3','Bas van Dijk',737, True, True, False, False),
    (150, 'cpphs','http://haskell.org/cpphs/','LGPL','Malcolm Wallace <Malcolm.Wallace@cs.york.ac.uk>',742, True, True, False, False),
    (151, 'dlist','http://code.haskell.org/~dons/code/dlist/','BSD3','Don Stewart',747, True, True, False, False),
    (152, 'resolve-trivial-conflicts','https://github.com/ElastiLotem/resolve-trivial-conflicts','GPL','Eyal Lotem',752, True, True, False, False),
    (153, 'GLURaw','http://www.haskell.org/haskellwiki/Opengl','BSD3','',757, True, True, False, False),
    (154, 'cairo','http://projects.haskell.org/gtk2hs/','BSD3','Axel Simon, Duncan Coutts',762, True, True, False, False),
    (155, 'pretty-simple','https://github.com/cdepillabout/pretty-simple','BSD3','Dennis Gosnell',767, True, True, False, False),
    (156, 'bifunctors','http://github.com/ekmett/bifunctors/','BSD3','Edward A. Kmett',772, True, True, False, False),
    (157, 'GLUT','http://www.haskell.org/HOpenGL/','BSD3','',777, True, True, False, False),
    (158, 'MagicHaskeller','http://nautilus.cs.miyazaki-u.ac.jp/~skata/MagicHaskeller.html','BSD3','Susumu Katayama',782, True, True, False, False),
    (159, 'aeson-schema','https://github.com/timjb/aeson-schema','MIT','Tim Baumann <tim@timbaumann.info>',787, True, True, False, False),
    (160, 'breve','https://github.com/rnhmjoj/breve','MIT','Rnhmjoj',792, True, True, False, False),
    (161, 'llvm-extra','http://code.haskell.org/~thielema/llvm-extra/','BSD3','Henning Thielemann <haskell@henning-thielemann.de>',797, True, True, False, False),
    (162, 'parsec','http://www.cs.uu.nl/~daan/parsec.html','BSD3','Daan Leijen <daan@cs.uu.nl>, Paolo Martini <paolo@nemail.it>',802, True, True, False, False),
    (163, 'haddock','http://www.haskell.org/haddock/','BSD3','Simon Marlow, David Waern',807, True, True, False, False),
    (164, 'pandoc-types','http://johnmacfarlane.net/pandoc','GPL','John MacFarlane',812, True, True, False, False),
    (165, 'prednote','http://github.com/massysett/prednote','BSD3','Omari Norman',817, True, True, False, False),
    (166, 'repa','http://repa.ouroborus.net','BSD3','The DPH Team',822, True, True, False, False),
    (167, 'cabal-macosx','http://github.com/gimbo/cabal-macosx','BSD3','Eric Kow <eric.kow@gmail.com> & Andy Gimblett <haskell@gimbo.org.uk>',827, True, True, False, False),
    (168, 'classy-prelude','https://github.com/snoyberg/classy-prelude','MIT','Michael Snoyman',832, False, True, False, False),
    (169, 'cmdargs','http://community.haskell.org/~ndm/cmdargs/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',837, True, True, False, False),
    (170, 'gloss','http://trac.haskell.org/gloss','MIT','Ben Lippmeier',842, True, True, False, False),
    (171, 'json-rpc-server','','MIT','',847, True, True, False, False),
    (172, 'vector-instances','http://github.com/ekmett/vector-instances','BSD3','Edward Kmett',852, True, False, False, False),
    (173, 'gi-javascriptcore','https://github.com/haskell-gi/haskell-gi','LGPL','Will Thompson, IÃ±aki GarcÃ­a Etxebarria and Jonas Platte',857, True, True, False, False),
    (174, 'snap','http://snapframework.com/','BSD3','James Sanders, Shu-yu Guo, Gregory Collins, Doug Beardsley',862, True, True, False, False),
    (175, 'RepLib','http://code.google.com/p/replib/','BSD3','Stephanie Weirich',867, False, True, False, False),
    (176, 'bytestring','http://www.cse.unsw.edu.au/~dons/fps.html','BSD3','Don Stewart, Duncan Coutts',872, True, True, False, False),
    (177, 'seqloc','http://www.ingolia-lab.org/software/seqloc/','MIT','Nick Ingolia',877, True, True, False, False),
    (178, 'RefSerialize','','BSD3','Alberto GÃ³mez Corona',882, True, True, False, False),
    (179, 'fast-tags','','BSD3','Evan Laforge',887, True, True, False, False),
    (180, 'mtl','','BSD3','Andy Gill',892, True, False, False, False),
    (181, 'ALUT','http://connect.creativelabs.com/openal/','BSD3','',897, True, True, False, False),
    (182, 'hledger-irr','','BSD3','Joachim Breitner <mail@joachim-breitner.de>',902, True, True, False, False),
    (183, 'ideas','http://ideas.cs.uu.nl/www/','GPL','Bastiaan Heeren, Alex Gerdes, Johan Jeuring',907, True, True, False, False),
    (184, 'liquidhaskell','http://goto.ucsd.edu/liquidhaskell','BSD3','Ranjit Jhala, Niki Vazou, Eric Seidel',912, True, True, False, False),
    (185, 'rattletrap','https://github.com/tfausak/rattletrap#readme','MIT','',917, False, True, False, False),
    (186, 'safe','http://community.haskell.org/~ndm/safe/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',922, True, True, False, False),
    (187, 'one-liner','https://github.com/sjoerdvisscher/one-liner','BSD3','Sjoerd Visscher',927, True, True, False, False),
    (188, 'pusher-http-haskell','https://github.com/pusher-community/pusher-http-haskell','MIT','Will Sewell',932, False, True, False, False),
    (189, 'xml-conduit','http://github.com/snoyberg/xml','BSD3','Michael Snoyman <michaels@suite-sol.com>, Aristid Breitkreuz <aristidb@googlemail.com>',937, True, True, False, False),
    (190, 'yesod-paginator','http://github.com/pbrisbin/yesod-paginator','BSD3','Patrick Brisbin',942, True, True, False, False),
    (191, 'esqueleto','https://github.com/meteficha/esqueleto','BSD3','Felipe Lessa',947, True, True, False, False),
    (192, 'idris','http://www.cs.st-andrews.ac.uk/~eb/Idris/','BSD3','Edwin Brady',952, True, True, False, False),
    (193, 'pdf-slave','https://github.com/NCrashed/pdf-slave#readme','BSD3','Anton Gushcha',957, True, True, False, False),
    (194, 'ply-loader','','BSD3','Anthony Cowley',962, True, True, False, False),
    (195, 'qr-imager','https://github.com/vmchale/QRImager#readme','BSD3','Vanessa McHale',967, True, True, False, False),
    (196, 'tagsoup','http://community.haskell.org/~ndm/tagsoup/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',972, True, True, False, False),
    (197, 'ixmonad','','BSD3','Dominic Orchard',977, False, True, False, False),
    (198, 'scalpel','https://github.com/fimad/scalpel','Apache','Will Coster',982, True, True, False, False),
    (199, 'enumerator','http://ianen.org/haskell/enumerator/','MIT','John Millikin <jmillikin@gmail.com>',987, True, True, False, False),
    (200, 'hslogger','http://software.complete.org/hslogger','LGPL','John Goerzen',992, True, True, False, False),
    (201, 'postgresql-simple','','BSD3','Bryan OSullivan, Leon P Smith',997, True, True, False, False),
    (202, 'vector-binary-instances','https://github.com/bos/vector-binary-instances','BSD3','Don Stewart',1002, True, True, False, False),
    (203, 'yesod-auth','http://docs.yesodweb.com/','BSD3','Michael Snoyman <michael@snoyman.com>',1007, True, True, False, True),
    (204, 'amazonka','https://github.com/brendanhay/amazonka','OtherLicense','Brendan Hay',1012, True, True, False, False),
    (205, 'cereal','','BSD3','Lennart Kolmodin <kolmodin@dtek.chalmers.se>,
Galois Inc.,
Lemmih <lemmih@gmail.com>',1017, True, True, False, False),
    (206, 'cryptohash','','BSD3','Vincent Hanquez',1022, True, True, False, False),
    (207, 'ghcjs-dom','','MIT','Hamish Mackenzie',1027, True, True, False, False),
    (208, 'hedis','https://github.com/informatikr/hedis','BSD3','Falko Peters',1032, True, True, False, False),
    (209, 'http2','','BSD3','Kazu Yamamoto <kazu@iij.ad.jp>',1037, True, True, False, False),
    (210, 'lambdacube-gl','http://lambdacube3d.com','BSD3','Csaba Hruska, Peter Divianszky',1042, True, True, False, False),
    (211, 'systemd','https://github.com/erebe/systemd','BSD3','ErÃ¨be',1047, True, True, False, False),
    (212, 'al','http://github.com/phaazon/al','BSD3','Dimitri Sabadie <dimitri.sabadie@gmail.com>',1052, True, False, False, False),
    (213, 'alex-meta','','BSD3','Jonas Duregard',1057, True, True, False, False),
    (214, 'glib','http://projects.haskell.org/gtk2hs/','LGPL','Axel Simon, Duncan Coutts',1062, False, True, False, False),
    (215, 'happstack-server','http://happstack.com','BSD3','Happstack team, HAppS LLC',1067, True, True, False, False),
    (216, 'rest-types','','BSD3','',1072, True, True, False, False),
    (217, 'tagged','http://github.com/ekmett/tagged','BSD3','Edward A. Kmett',1077, True, True, False, False),
    (218, 'vivid','','GPL','Tom Murphy',1082, False, True, False, False),
    (219, 'aws','http://github.com/aristidb/aws','BSD3','Aristid Breitkreuz',1087, True, True, False, False),
    (220, 'conduit-combinators','https://github.com/fpco/conduit-combinators','MIT','Michael snoyman',1092, True, True, False, False),
    (221, 'hashable-extras','http://github.com/analytics/hashable-extras/','BSD3','Edward A. Kmett',1097, True, True, False, False),
    (222, 'lambda-options','https://github.com/thomaseding/lambda-options','OtherLicense','Thomas Eding',1102, True, True, False, False),
    (223, 'relational-query-HDBC','http://khibino.github.io/haskell-relational-record/','BSD3','Kei Hibino, Shohei Murayama, Shohei Yasutake, Sho KURODA',1107, True, True, False, False),
    (224, 'snap-core','http://snapframework.com/','BSD3','James Sanders, Shu-yu Guo, Gregory Collins, Doug Beardsley',1112, True, True, False, False),
    (225, 'uuid','http://community.haskell.org/~aslatter/code/uuid/','BSD3','Antoine Latter',1117, True, True, False, False),
    (226, 'RNAlien','','GPL','Florian Eggenhofer',1122, True, True, False, False),
    (227, 'singletons','http://www.cis.upenn.edu/~eir/packages/singletons','BSD3','Richard Eisenberg <eir@cis.upenn.edu>',1127, True, True, False, False),
    (228, 'intro','https://github.com/minad/intro#readme','MIT','Daniel Mendler <mail@daniel-mendler.de>',1132, True, True, False, False),
    (229, 'syb','http://www.cs.uu.nl/wiki/GenericProgramming/SYB','BSD3','Ralf Lammel, Simon Peyton Jones',1137, True, True, False, False),
    (230, 'fgl','http://web.engr.oregonstate.edu/~erwig/fgl/haskell','BSD3','Martin Erwig, Ivan Lazar Miljenovic',1142, True, True, False, False),
    (231, 'linear','http://github.com/ekmett/linear/','BSD3','Edward A. Kmett',1147, True, True, False, False),
    (232, 'memory','https://github.com/vincenthz/hs-memory','BSD3','Vincent Hanquez <vincent@snarc.org>',1152, True, True, False, False),
    (233, 'rasa','https://github.com/ChrisPenner/rasa#readme','MIT','Chris Penner',1157, True, True, False, False),
    (234, 'yi','http://haskell.org/haskellwiki/Yi','GPL','AUTHORS',1162, True, True, True, False),
    (235, 'cmark','https://github.com/jgm/commonmark-hs','BSD3','John MacFarlane',1167, True, True, False, False),
    (236, 'halive','https://github.com/lukexi/halive','BSD2','Luke Iannini',1172, True, True, False, False),
    (237, 'happy-meta','','BSD3','Jonas Duregard',1177, True, False, False, False),
    (238, 'heist','http://snapframework.com/','BSD3','Doug Beardsley, Gregory Collins',1182, True, True, False, False),
    (239, 'monad-control','https://github.com/basvandijk/monad-control/','BSD3','Bas van Dijk, Anders Kaseorg',1187, True, False, False, False),
    (240, 'monad-logger','https://github.com/kazu-yamamoto/logger','MIT','Michael Snoyman',1192, False, True, False, False),
    (241, 'trifecta','http://github.com/ekmett/trifecta/','BSD3','Edward A. Kmett',1197, True, True, False, False),
    (242, 'Hoed','http://maartenfaddegon.nl','BSD3','Maarten Faddegon',1202, False, True, False, False),
    (243, 'MonadRandom','','OtherLicense','Cale Gibbard and others',1207, True, True, False, False),
    (244, 'blaze-builder','http://github.com/jaspervdj/blaze-builder','BSD3','Jasper Van der Jeugt, Simon Meier',1212, True, True, False, False),
    (245, 'hashed-storage','','BSD3','Petr Rockai <me@mornfall.net>',1217, True, True, False, False),
    (246, 'hjsonschema','https://github.com/seagreen/hjsonschema','MIT','Ian Grant Jeffries',1222, True, True, False, False),
    (247, 'jsaddle','','MIT','Hamish Mackenzie',1227, True, True, False, False),
    (248, 'relational-record','http://khibino.github.io/haskell-relational-record/','BSD3','Kei Hibino',1232, True, True, False, False),
    (249, 'time-patterns','https://bitbucket.org/jfmueller/time-patterns','BSD3','Jann MÃ¼ller, Moritz Kiefer',1237, True, True, False, False),
    (250, 'unlit','','BSD3','Pepijn Kokke',1242, True, True, False, False),
    (251, 'comonad','http://comonad.com/reader/','BSD3','Edward A. Kmett',1247, True, True, False, False),
    (252, 'distributed-process','http://github.com/haskell-distributed/distributed-process','BSD3','Duncan Coutts, Nicolas Wu, Edsko de Vries',1252, True, True, False, False),
    (253, 'ginger','https://bitbucket.org/tdammers/ginger','MIT','Tobias Dammers',1257, True, True, False, False),
    (254, 'reroute','http://github.com/agrafix/reroute','MIT','Alexander Thiemann <mail@agrafix.net>, Tim Baumann <tim@timbaumann.info>',1262, True, True, False, False),
    (255, 'Crypto','','OtherLicense','Dominic Steinitz',1267, True, True, False, False),
    (256, 'hspec-core','http://hspec.github.io/','MIT','',1272, True, True, False, False),
    (257, 'octane','https://github.com/tfausak/octane','MIT','',1277, True, True, False, False),
    (258, 'vty','http://trac.haskell.org/vty/','BSD3','Stefan ORear',1282, False, True, False, False),
    (259, 'x509','http://github.com/vincenthz/hs-certificate','BSD3','Vincent Hanquez <vincent@snarc.org>',1287, True, True, False, False),
    (260, 'HaXml','http://www.cs.york.ac.uk/fp/HaXml/','LGPL','Malcolm Wallace <Malcolm.Wallace@cs.york.ac.uk>',1292, True, True, False, False),
    (261, 'JuicyPixels','https://github.com/Twinside/Juicy.Pixels','BSD3','Vincent Berthoux',1297, True, True, False, False),
    (262, 'air','https://github.com/nfjinjing/air','BSD3','Jinjing Wang',1302, True, True, False, False),
    (263, 'concurrent-machines','','BSD3','Anthony Cowley',1307, True, True, False, False),
    (264, 'fclabels','','BSD3','Sebastiaan Visser, Erik Hesselink, Chris Eidhof, Sjoerd Visscher.',1312, True, True, False, False),
    (265, 'heyefi','https://github.com/ryantm/heyefi','PublicDomain','Ryan Mulligan',1317, False, True, False, False),
    (266, 'rest-wai','','BSD3','',1322, True, True, False, False),
    (267, 'hashtables','http://github.com/gregorycollins/hashtables','BSD3','Gregory Collins',1327, True, True, False, False),
    (268, 'machines-io','http://github.com/aloiscochard/machines-io','Apache','Alois Cochard',1332, True, True, False, False),
    (269, 'xmonad','http://xmonad.org','BSD3','Spencer Janssen',1337, True, True, False, False),
    (270, 'SHA','','BSD3','Adam Wick <awick@galois.com>',1342, True, True, False, False),
    (271, 'cgi','','BSD3','Bjorn Bringert',1347, True, True, False, False),
    (272, 'free','git://github.com/ekmett/free/','BSD3','Edward A. Kmett',1352, True, True, False, False),
    (273, 'tar','','BSD3','Bjorn Bringert <bjorn@bringert.net>
Duncan Coutts <duncan@haskell.org>',1357, True, True, False, False),
    (274, 'LDAP','http://software.complete.org/ldap-haskell','BSD3','John Goerzen',1362, True, True, False, False),
    (275, 'http-types','https://github.com/aristidb/http-types','BSD3','Aristid Breitkreuz',1367, True, True, False, False),
    (276, 'instrument-chord','https://github.com/xpika/chord','GPL','Alan Hawkins',1372, True, True, False, False),
    (277, 'lifted-base','https://github.com/basvandijk/lifted-base','BSD3','Bas van Dijk, Anders Kaseorg',1377, True, True, False, False),
    (278, 'range-set-list','https://github.com/phadej/range-set-list','MIT','Oleg Grenrus',1382, False, True, False, False),
    (279, 'references','https://github.com/lazac/references','BSD3','Boldizsar Nemeth',1387, True, True, False, False),
    (280, 'rss','https://github.com/basvandijk/rss','PublicDomain','Jeremy Shaw, Bjorn Bringert',1392, True, True, False, False),
    (281, 'Agda','http://wiki.portal.chalmers.se/agda/','OtherLicense','Ulf Norell, Nils Anders Danielsson, Catarina Coquand, Makoto Takeyama, Andreas Abel, Darin Morrison...',1397, False, True, False, False),
    (282, 'ShellCheck','http://www.shellcheck.net/','OtherLicense','Vidar Holen',1402, True, True, False, False),
    (283, 'ad','http://comonad.com/reader/','BSD3','Edward Kmett',1407, True, True, False, False),
    (284, 'blaze-markup','http://jaspervdj.be/blaze','BSD3','Jasper Van der Jeugt, Simon Meier, Deepak Jois',1412, True, True, False, False),
    (285, 'classy-prelude-yesod','https://github.com/snoyberg/classy-prelude','MIT','Michael Snoyman',1417, True, True, False, False),
    (286, 'clckwrks','http://www.clckwrks.com/','BSD3','Jeremy Shaw',1422, True, True, False, False),
    (287, 'pango','http://projects.haskell.org/gtk2hs/','LGPL','Axel Simon, Duncan Coutts',1427, True, True, False, False),
    (288, 'parallel','','BSD3','',1432, True, True, False, False),
    (289, 'postgresql-binary','https://github.com/nikita-volkov/postgresql-binary','MIT','Nikita Volkov <nikita.y.volkov@mail.ru>',1437, True, True, False, False),
    (290, 'semver','https://github.com/brendanhay/semver','OtherLicense','Brendan Hay',1442, True, True, False, False),
    (291, 'aeson-extra','https://github.com/phadej/aeson-extra#readme','BSD3','Oleg Grenrus <oleg.grenrus@iki.fi>',1447, True, True, False, False),
    (292, 'clit','https://github.com/vmchale/command-line-tweeter#readme','BSD3','Vanessa McHale',1452, True, True, False, False),
    (293, 'data-msgpack','http://msgpack.org/','BSD3','Hideyuki Tanaka',1457, True, True, False, False),
    (294, 'hslua','','BSD3','Gracjan Polak <gracjanpolak@gmail.com>',1462, False, True, False, False),
    (295, 'hspec-expectations','https://github.com/sol/hspec-expectations#readme','MIT','Simon Hengel <sol@typeful.net>',1467, True, True, False, False),
    (296, 'json-rpc-client','https://github.com/grayjay/json-rpc-client','MIT','Kristen Kozak',1472, True, True, False, False),
    (297, 'language-javascript','http://github.com/alanz/language-javascript','BSD3','Alan Zimmerman',1477, True, True, False, False),
    (298, 'publicsuffix','https://github.com/wereHamster/publicsuffix-haskell/','MIT','Tomas Carnecky',1482, True, True, False, False),
    (299, 'securemem','http://github.com/vincenthz/hs-securemem','BSD3','Vincent Hanquez <vincent@snarc.org>',1487, True, True, False, False),
    (300, 'stm','','BSD3','',1492, True, True, False, False);
ALTER SEQUENCE package_packageid_seq RESTART WITH 301;