INSERT INTO Package VALUES
    (0, 'egison','http://hagi.is.s.u-tokyo.ac.jp/~egi/egison/','MIT','Satoshi Egi',3, True, True, False, False),
    (1, 'timeplot','http://haskell.org/haskellwiki/Timeplot','BSD3','Eugene Kirpichov <ekirpichov@gmail.com>',7, True, True, False, False),
    (2, 'sbv','http://leventerkok.github.com/sbv/','BSD3','Levent Erkok',8, True, True, False, False),
    (3, 'HTTP','http://www.haskell.org/http/','BSD3','Warrick Gray <warrick.gray@hotmail.com>',12, True, True, False, False),
    (4, 'conduit','http://github.com/snoyberg/conduit','BSD3','Michael Snoyman',16, True, True, False, False),
    (5, 'hledger-web','http://hledger.org','GPL','Simon Michael <simon@joyful.com>',20, True, True, False, False),
    (6, 'resourcet','http://github.com/snoyberg/conduit','BSD3','Michael Snoyman',24, True, True, False, False),
    (7, 'shakespeare','http://www.yesodweb.com/book/templates','BSD3','Michael Snoyman <michael@snoyman.com>',28, True, True, False, False),
    (8, 'relational-query','http://twitter.com/khibino','BSD3','Kei Hibino',32, True, True, False, False),
    (9, 'hledger','http://hledger.org','GPL','Simon Michael <simon@joyful.com>',36, True, True, False, False),
    (10, 'lens','http://github.com/ekmett/lens/','BSD3','Edward A. Kmett',40, True, True, False, False),
    (11, 'containers','','BSD3','',44, True, True, False, False),
    (12, 'scientific','https://github.com/basvandijk/scientific','BSD3','Bas van Dijk',48, True, True, False, False),
    (13, 'cblrepo','','OtherLicense','Magnus Therning',52, True, True, False, False),
    (14, 'aeson','http://github.com/mailrank/aeson','BSD3','Bryan OSullivan <bos@mailrank.com>',56, True, True, False, False),
    (15, 'semigroupoids','http://github.com/ekmett/semigroupoids','BSD3','Edward A. Kmett',60, True, True, False, False),
    (16, 'persistent-template','http://www.yesodweb.com/book/persistent','BSD3','Michael Snoyman <michael@snoyman.com>',64, True, True, False, False),
    (17, 'text','','BSD3','Tom Harper <rtharper@aftereternity.co.uk>',68, False, True, False, False),
    (18, 'http-client','https://github.com/snoyberg/http-client','MIT','Michael Snoyman',72, True, False, False, False),
    (19, 'Cabal','http://www.haskell.org/cabal/','BSD3','Isaac Jones <ijones@syntaxpolice.org>',76, True, True, False, False),
    (20, 'base','','BSD3','',80, True, True, False, False),
    (21, 'haskell-src-meta','','BSD3','Matt Morrow',84, True, True, False, False),
    (22, 'scotty','https://github.com/scotty-web/scotty','BSD3','Andrew Farmer <afarmer@ittc.ku.edu>',88, True, True, False, False),
    (23, 'diagrams-contrib','http://projects.haskell.org/diagrams/','BSD3','Various',92, True, True, False, False),
    (24, 'pandoc','http://sophos.berkeley.edu/macfarlane/pandoc','GPL','John MacFarlane <jgm@berkeley.edu>',96, True, True, False, False),
    (25, 'wai-routes','https://github.com/ajnsit/wai-routes','MIT','Anupam Jain',100, False, True, False, False),
    (26, 'cuda','','BSD3','Trevor L. McDonell <tmcdonell@cse.unsw.edu.au>',104, True, True, False, False),
    (27, 'type-natural','https://github.com/konn/type-natural','BSD3','Hiromi ISHII',108, True, True, False, False),
    (28, 'cabal-install','','BSD3','Lemmih <lemmih@gmail.com>
Paolo Martini <paolo@nemail.it>
Bjorn Bringert <bjorn@bringert.net>
Isaac Potoczny-Jones <ijones@syntaxpolice.org>
Duncan Coutts <duncan@haskell.org>',112, True, True, False, True),
    (29, 'attoparsec','','BSD3','Bryan OSullivan <bos@serpentine.com>',116, True, True, False, False),
    (30, 'either','http://github.com/ekmett/either/','BSD3','Edward A. Kmett',120, False, True, False, False),
    (31, 'pontarius-xmpp','http://www.pontarius.org/','LGPL','Jon Kristensen, Mahdi Abdinejadi',124, True, True, False, False),
    (32, 'hlint','http://community.haskell.org/~ndm/hlint/','GPL','Neil Mitchell <ndmitchell@gmail.com>',128, True, True, False, False),
    (33, 'git-annex','http://git-annex.branchable.com/','GPL','Joey Hess',132, True, True, False, False),
    (34, 'binary','http://www.cse.unsw.edu.au/~dons/binary.html','BSD3','Lennart Kolmodin <kolmodin@dtek.chalmers.se>',136, True, True, False, False),
    (35, 'protocol-buffers','http://hackage.haskell.org/cgi-bin/hackage-scripts/package/protocol-buffers','BSD3','Christopher Edward Kuklewicz',140, False, True, False, False),
    (36, 'warp','http://github.com/snoyberg/warp','BSD3','Michael Snoyman, Matt Brown',144, True, True, False, False),
    (37, 'network','','BSD3','',148, True, True, False, False),
    (38, 'purescript','','MIT','Phil Freeman <paf31@cantab.net>',152, True, True, False, False),
    (39, 'rainbow','http://github.com/massysett/rainbow','BSD3','Omari Norman',156, True, True, False, False),
    (40, 'uhc-util','https://github.com/UU-ComputerScience/uhc-utils','BSD3','Atze Dijkstra',160, True, True, False, False),
    (41, 'github','https://github.com/mike-burns/github','BSD3','Mike Burns',164, True, True, False, False),
    (42, 'ncurses','http://john-millikin.com/software/bindings/ncurses/','GPL','John Millikin <jmillikin@gmail.com>',168, True, True, False, False),
    (43, 'tls','http://github.com/vincenthz/hs-tls','BSD3','Vincent Hanquez <vincent@snarc.org>',172, True, True, False, False),
    (44, 'yaml','http://github.com/snoyberg/yaml/tree/master','BSD3','Michael Snoyman <michael@snoyman.com>',176, True, True, False, False),
    (45, 'preamble','https://github.com/swift-nav/preamble','MIT','Swift Navigation Inc.',180, True, True, False, False),
    (46, 'persistent-sqlite','http://docs.yesodweb.com/persistent/','BSD3','Michael Snoyman <michael@snoyman.com>',184, True, True, False, False),
    (47, 'safecopy','http://acid-state.seize.it/safecopy','PublicDomain','David Himmelstrup',188, True, True, False, False),
    (48, 'haskell-src-exts','http://code.haskell.org/HSP/haskell-src-exts','BSD3','Niklas Broberg',192, True, True, False, False),
    (49, 'time','http://semantic.org/TimeLib/','BSD3','Ashley Yakeley',196, True, True, False, False),
    (50, 'QuickCheck','http://www.math.chalmers.se/~rjmh/QuickCheck/','BSD3','Koen Classen and John Hughes',200, True, True, False, False),
    (51, 'rethinkdb','http://github.com/atnnn/haskell-rethinkdb','Apache','Etienne Laurin',204, False, True, False, False),
    (52, 'repa-io','http://repa.ouroborus.net','BSD3','The DPH Team',208, False, True, False, False),
    (53, 'snaplet-fay','https://github.com/faylang/snaplet-fay','BSD3','Adam Bergmark',212, True, True, False, False),
    (54, 'bamboo','http://github.com/nfjinjing/bamboo/tree/master','GPL','Wang, Jinjing',216, True, True, False, False),
    (55, 'uhc-light','https://github.com/UU-ComputerScience/uhc','BSD3','Atze Dijkstra',220, True, True, False, False),
    (56, 'hoogle','http://www.haskell.org/hoogle/','GPL','Neil Mitchell <ndmitchell@gmail.com>',224, True, True, False, False),
    (57, 'constraints','http://github.com/ekmett/constraints/','BSD3','Edward A. Kmett',228, True, True, False, False),
    (58, 'shake','http://community.haskell.org/~ndm/shake/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',232, True, True, False, False),
    (59, 'shellmate','http://github.com/valderman/shellmate','BSD3','Anton Ekblad',236, True, True, False, False),
    (60, 'HDBC-mysql','http://www.maubi.net/~waterson/hacks/hdbc-mysql.html','LGPL','Chris Waterson',240, True, True, False, False),
    (61, 'fltkhs','http://github.com/deech/fltkhs','MIT','Aditya Siram',244, True, True, False, False),
    (62, 'repa-algorithms','http://repa.ouroborus.net','BSD3','The DPH Team',248, True, True, False, False),
    (63, 'hspec','http://hspec.github.io/','MIT','',252, True, True, False, False),
    (64, 'protocol-buffers-descriptor','http://hackage.haskell.org/cgi-bin/hackage-scripts/package/protocol-buffers','BSD3','Christopher Edward Kuklewicz',256, True, True, False, False),
    (65, 'semigroups','http://comonad.com/reader/','BSD3','Edward A. Kmett',260, True, True, False, False),
    (66, 'threepenny-gui','http://github.com/HeinrichApfelmus/threepenny-gui','BSD3','Chris Done, Heinrich Apfelmus',264, True, True, False, False),
    (67, 'secp256k1','http://github.com/haskoin/secp256k1#readme','PublicDomain','Jean-Pierre Rupp',268, True, True, False, False),
    (68, 'friday','https://github.com/RaphaelJ/friday','LGPL','Raphael Javaux <raphaeljavaux[at]gmail.com>',272, True, True, False, False),
    (69, 'persistent-postgresql','http://docs.yesodweb.com/persistent/','BSD3','Michael Snoyman <michael@snoyman.com>',276, False, True, False, False),
    (70, 'rethinkdb-client-driver','https://github.com/wereHamster/rethinkdb-client-driver','MIT','Tomas Carnecky',280, True, True, False, False),
    (71, 'streaming-bytestring','','BSD3','michaelt',284, True, True, False, False),
    (72, 'highlighting-kate','http://johnmacfarlane.net/highlighting-kate','GPL','John MacFarlane',288, True, True, False, False),
    (73, 'RSA','','BSD3','Adam Wick <awick@galois.com>',292, True, True, False, False),
    (74, 'haskell-docs','http://github.com/chrisdone/haskell-docs','BSD3','Chris Done',296, True, True, False, False),
    (75, 'persistent','http://docs.yesodweb.com/persistent/','BSD3','Michael Snoyman <michael@snoyman.com>',300, False, True, False, False),
    (76, 'random-fu','http://code.haskell.org/~mokus/random-fu','PublicDomain','James Cook <james.cook@usma.edu>',304, True, False, False, False),
    (77, 'vector','http://darcs.haskell.org/vector','BSD3','Roman Leshchinskiy',308, True, True, False, False),
    (78, 'shakers','https://github.com/swift-nav/shakers','MIT','Swift Navigation Inc.',312, False, False, False, False),
    (79, 'yaml-light-lens','','BSD3','Anthony Cowley',316, False, True, False, False),
    (80, 'sandi','http://hackage.haskell.org/package/sandi','BSD3','Magnus Therning',320, True, True, False, False),
    (81, 'yesod','http://docs.yesodweb.com/yesod/','BSD3','Michael Snoyman <michael@snoyman.com>',324, True, True, False, False),
    (82, 'conduit-extra','http://github.com/snoyberg/conduit','MIT','Michael Snoyman',328, True, True, False, False),
    (83, 'http-conduit','http://www.yesodweb.com/book/http-conduit','BSD3','Michael Snoyman <michael@snoyman.com>',332, True, True, False, False),
    (84, 'directory','','BSD3','',336, True, True, False, False),
    (85, 'gl','','BSD3','Edward A. Kmett, GabrÃ­el ArthÃºr PÃ©tursson, Sven Panne',340, True, True, False, False),
    (86, 'hakyll','http://jaspervdj.be/hakyll','BSD3','Jasper Van der Jeugt',344, True, True, False, False),
    (87, 'hint','','BSD3','Daniel Gorin',348, True, True, False, False),
    (88, 'simple-effects','https://gitlab.com/LukaHorvat/simple-effects','BSD3','Luka Horvat',352, True, True, False, False),
    (89, 'OpenGLRaw','http://www.haskell.org/HOpenGL/','BSD3','',356, True, True, False, False),
    (90, 'blaze-html','http://jaspervdj.be/blaze','BSD3','Jasper Van der Jeugt, Simon Meier',360, True, True, False, False),
    (91, 'computational-algebra','https://github.com/konn/computational-algebra','BSD3','Hiromi ISHII',364, True, True, False, False),
    (92, 'hmatrix','http://alberrto.googlepages.com/gslhaskell','GPL','Alberto Ruiz',368, True, True, False, False),
    (93, 'pointfree','http://haskell.org/haskellwiki/Pointfree','OtherLicense','Thomas JÃ¤ger',372, True, True, False, False),
    (94, 'unordered-containers','','BSD3','Johan Tibell <johan.tibell@gmail.com>',376, False, True, False, False),
    (95, 'cabal2nix','http://github.com/peti/cabal2nix','BSD3','Peter Simons <simons@cryp.to>',380, True, True, False, False),
    (96, 'wai','http://github.com/snoyberg/wai','BSD3','Michael Snoyman',384, True, True, False, False),
    (97, 'distributive','http://github.com/ekmett/distributive/','BSD3','Edward A. Kmett',388, True, True, False, False),
    (98, 'rest-client','','BSD3','',392, True, True, False, False),
    (99, 'rest-happstack','','BSD3','',396, True, True, False, False),
    (100, 'YamlReference','www.ben-kiki.org/oren/YamlReference','LGPL','Oren Ben-Kiki',400, True, True, False, False),
    (101, 'sdl2','','BSD3','GabrÃ­el ArthÃºr PÃ©tursson',404, True, True, False, False),
    (102, 'yesod-core','http://www.yesodweb.com/','BSD3','Michael Snoyman <michael@snoyman.com>',408, True, True, False, False),
    (103, 'zlib','','BSD3','Duncan Coutts <duncan@haskell.org>',412, True, True, False, False),
    (104, 'haskeline','http://trac.haskell.org/haskeline','BSD3','Judah Jacobson',416, True, True, False, False),
    (105, 'texmath','http://github.com/jgm/texmath','GPL','John MacFarlane',420, True, True, False, False),
    (106, 'Unique','','BSD3','Volodymyr Yaschenko',424, True, True, False, False),
    (107, 'legion','https://github.com/taphu/legion','Apache','Rick Owens',428, True, True, False, False),
    (108, 'rainbox','http://www.github.com/massysett/rainbox','BSD3','Omari Norman',432, True, True, False, False),
    (109, 'damnpacket','','MIT','Jude Taylor',436, True, True, False, False),
    (110, 'quickcheck-instances','https://github.com/aslatter/qc-instances','BSD3','Antoine Latter',440, True, True, False, False),
    (111, 'wolf','https://github.com/swift-nav/wolf','MIT','Swift Navigation Inc.',444, True, True, False, False),
    (112, 'criterion','','BSD3','Bryan OSullivan <bos@serpentine.com>',448, True, True, False, False),
    (113, 'cryptonite','https://github.com/vincenthz/cryptonite','BSD3','Vincent Hanquez <vincent@snarc.org>',452, False, True, False, False),
    (114, 'transformers','','BSD3','Andy Gill',456, True, True, False, False),
    (115, 'wai-extra','http://github.com/snoyberg/wai-extra','BSD3','Michael Snoyman',460, True, True, False, False),
    (116, 'OpenGL','http://www.haskell.org/HOpenGL/','BSD3','',464, True, True, False, False),
    (117, 'Win32','','BSD3','Alastair Reid',468, True, True, False, False),
    (118, 'darcs','http://darcs.net/','GPL','David Roundy <droundy@darcs.net>, <darcs-users@darcs.net>',472, True, True, False, False),
    (119, 'heckle','https://github.com/2016rshah/heckle','MIT','Rushi Shah',476, True, True, False, False),
    (120, 'lzma-conduit','http://github.com/alphaHeavy/lzma-conduit','BSD3','Nathan Howell <nhowell@alphaheavy.com>',480, True, True, False, False),
    (121, 'yesod-bin','http://www.yesodweb.com/','MIT','Michael Snoyman <michael@snoyman.com>',484, True, True, False, True),
    (122, 'cabal-rpm','http://www.serpentine.com/software/cabal-rpm/','GPL','Bryan OSullivan <bos@serpentine.com>',488, True, True, False, False),
    (123, 'llvm-general','','BSD3','Benjamin S.Scarlet <fgthb0@greynode.net>',492, True, True, False, False),
    (124, 'pureMD5','','BSD3','Thomas DuBuisson <thomas.dubuisson@gmail.com>',496, True, True, False, False),
    (125, 'purescript-bridge','','AGPL','Robert Klotzner',500, True, True, False, False),
    (126, 'sendfile','http://patch-tag.com/r/sendfile','BSD3','Matthew Elder <matt@mattelder.org>',504, True, True, False, False),
    (127, 'ghc-mod','http://www.mew.org/~kazu/proj/ghc-mod/','BSD3','Kazu Yamamoto <kazu@iij.ad.jp>
Daniel GrÃ¶ber <dxld@darkboxed.org>
Alejandro Serrano <trupill@gmail.com>',508, True, True, False, False),
    (128, 'machinecell','http://github.com/as-capabl/machinecell','BSD3','Hidenori Azuma',512, True, True, False, False),
    (129, 'lentil','http://www.ariis.it/static/articles/lentil/page.html','GPL','Francesco Ariis <fa-ml@ariis.it>',516, False, True, False, False),
    (130, 'pipes','','BSD3','Gabriel Gonzalez',520, True, True, False, False),
    (131, 'postgresql-libpq','http://github.com/lpsmith/postgresql-libpq','BSD3','Grant Monroe, Leon P Smith',524, True, True, False, False),
    (132, 'shelly','https://github.com/yesodweb/Shelly.hs','BSD3','Greg Weber, Petr Rockai',528, True, True, False, False),
    (133, 'crypto-enigma','https://github.com/orome/crypto-enigma-hs','BSD3','Roy Levien',530, True, True, False, False),
    (134, 'liquid-fixpoint','https://github.com/ucsd-progsys/liquid-fixpoint','BSD3','Ranjit Jhala, Niki Vazou, Eric Seidel',534, False, True, False, False),
    (135, 'pandoc-citeproc','','BSD3','John MacFarlane, Andrea Rossato',538, True, True, True, False),
    (136, 'rest-snap','','BSD3','',542, True, True, False, False),
    (137, 'time-exts','https://github.com/enzoh/time-exts','BSD3','Enzo Haussecker <ehaussecker@gmail.com>',546, True, True, False, False),
    (138, 'HUnit','http://hunit.sourceforge.net/','BSD3','Dean Herington',550, True, True, False, False),
    (139, 'extra','https://github.com/ndmitchell/extra#readme','BSD3','Neil Mitchell <ndmitchell@gmail.com>',554, True, True, False, False),
    (140, 'hashable','http://github.com/tibbe/hashable','BSD3','Milan Straka <fox@ucw.cz>
Johan Tibell <johan.tibell@gmail.com>',558, True, False, False, False),
    (141, 'irc-core','https://github.com/glguy/irc-core','BSD3','Eric Mertens',562, True, True, False, False),
    (142, 'phoityne-vscode','https://sites.google.com/site/phoityne/vscode','BSD3','phoityne_hs',566, True, True, False, False),
    (143, 'pretty-show','http://wiki.github.com/yav/pretty-show','BSD3','Iavor S. Diatchki',570, True, True, False, False),
    (144, 'web3','https://github.com/airalab/hs-web3#readme','BSD3','Alexander Krupenkin',574, False, True, False, False),
    (145, 'alex','http://www.haskell.org/alex/','BSD3','Chris Dornan and Simon Marlow',578, False, True, False, False),
    (146, 'http-api-data','http://github.com/fizruk/http-api-data','BSD3','Nickolay Kudasov <nickolay.kudasov@gmail.com>',582, True, True, False, False),
    (147, 'streaming-commons','https://github.com/fpco/streaming-commons','MIT','Michael Snoyman, Gabriel Gonzalez',586, True, True, False, False),
    (148, 'case-insensitive','','BSD3','Bas van Dijk',590, True, True, False, False),
    (149, 'cpphs','http://haskell.org/cpphs/','LGPL','Malcolm Wallace <Malcolm.Wallace@cs.york.ac.uk>',594, True, True, False, False),
    (150, 'dlist','http://www.cse.unsw.edu.au/~dons/dlist.html','BSD3','Don Stewart',598, True, True, False, False),
    (151, 'resolve-trivial-conflicts','https://github.com/ElastiLotem/resolve-trivial-conflicts','GPL','Eyal Lotem',602, True, True, False, False),
    (152, 'GLURaw','http://www.haskell.org/haskellwiki/Opengl','BSD3','',606, True, True, False, False),
    (153, 'cairo','http://projects.haskell.org/gtk2hs/','BSD3','Axel Simon, Duncan Coutts',610, True, True, True, False),
    (154, 'pretty-simple','https://github.com/cdepillabout/pretty-simple','BSD3','Dennis Gosnell',614, True, True, False, False),
    (155, 'bifunctors','http://github.com/ekmett/bifunctors/','BSD3','Edward A. Kmett',618, True, True, False, False),
    (156, 'GLUT','http://www.haskell.org/HOpenGL/','BSD3','',622, True, True, False, False),
    (157, 'MagicHaskeller','http://nautilus.cs.miyazaki-u.ac.jp/~skata/MagicHaskeller.html','BSD3','Susumu Katayama',626, True, True, False, False),
    (158, 'aeson-schema','https://github.com/timjb/aeson-schema','MIT','Tim Baumann <tim@timbaumann.info>',630, True, True, False, False),
    (159, 'breve','https://github.com/rnhmjoj/breve','MIT','Rnhmjoj',634, True, True, False, False),
    (160, 'llvm-extra','http://code.haskell.org/~thielema/llvm-extra/','BSD3','Henning Thielemann <haskell@henning-thielemann.de>',638, True, True, False, False),
    (161, 'parsec','http://www.cs.uu.nl/~daan/parsec.html','BSD3','Daan Leijen <daan@cs.uu.nl>, Paolo Martini <paolo@nemail.it>',642, True, True, False, False),
    (162, 'haddock','http://www.haskell.org/haddock/','BSD3','Simon Marlow, David Waern',646, True, True, False, False),
    (163, 'pandoc-types','http://johnmacfarlane.net/pandoc','GPL','John MacFarlane',650, True, True, False, False),
    (164, 'prednote','http://github.com/massysett/prednote','BSD3','Omari Norman',654, True, True, False, False),
    (165, 'repa','http://trac.haskell.org/repa','BSD3','The DPH Team',658, True, True, False, False),
    (166, 'cabal-macosx','http://github.com/gimbo/cabal-macosx','BSD3','Eric Kow <eric.kow@gmail.com> & Andy Gimblett <haskell@gimbo.org.uk>',662, True, True, False, False),
    (167, 'classy-prelude','https://github.com/snoyberg/classy-prelude','MIT','Michael Snoyman',666, True, False, False, False),
    (168, 'cmdargs','http://community.haskell.org/~ndm/cmdargs/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',670, True, True, False, False),
    (169, 'gloss','http://trac.haskell.org/gloss','MIT','Ben Lippmeier',674, True, True, False, False),
    (170, 'json-rpc-server','','MIT','',678, True, True, False, False),
    (171, 'vector-instances','http://github.com/ekmett/vector-instances','BSD3','Edward Kmett',682, False, True, False, False),
    (172, 'gi-javascriptcore','https://github.com/haskell-gi/haskell-gi','LGPL','Will Thompson, IÃ±aki GarcÃ­a Etxebarria and Jonas Platte',686, True, True, False, False),
    (173, 'snap','http://snapframework.com/','BSD3','James Sanders, Shu-yu Guo, Gregory Collins, Doug Beardsley',690, False, True, False, False),
    (174, 'RepLib','http://code.google.com/p/replib/','BSD3','Stephanie Weirich',694, True, True, False, False),
    (175, 'bytestring','http://www.cse.unsw.edu.au/~dons/fps.html','BSD3','Don Stewart, Duncan Coutts',698, True, True, False, False),
    (176, 'seqloc','http://www.ingolia-lab.org/software/seqloc/','MIT','Nick Ingolia',702, True, True, False, False),
    (177, 'RefSerialize','','BSD3','Alberto GÃ³mez Corona',706, True, True, False, False),
    (178, 'fast-tags','','BSD3','Evan Laforge',710, True, True, False, False),
    (179, 'mtl','','BSD3','Andy Gill',714, True, True, False, False),
    (180, 'ALUT','http://connect.creativelabs.com/openal/','BSD3','',718, True, True, False, False),
    (181, 'hledger-irr','','BSD3','Joachim Breitner <mail@joachim-breitner.de>',722, True, True, False, False),
    (182, 'ideas','http://ideas.cs.uu.nl/www/','GPL','Bastiaan Heeren, Alex Gerdes, Johan Jeuring',726, True, True, False, False),
    (183, 'liquidhaskell','http://goto.ucsd.edu/liquidhaskell','BSD3','Ranjit Jhala, Niki Vazou, Eric Seidel',730, True, True, False, False),
    (184, 'rattletrap','https://github.com/tfausak/rattletrap#readme','MIT','',734, True, True, False, False),
    (185, 'safe','http://community.haskell.org/~ndm/safe/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',738, True, True, False, False),
    (186, 'one-liner','https://github.com/sjoerdvisscher/one-liner','BSD3','Sjoerd Visscher',742, True, True, False, False),
    (187, 'pusher-http-haskell','https://github.com/pusher-community/pusher-http-haskell','MIT','Will Sewell',746, True, True, False, False),
    (188, 'xml-conduit','http://github.com/snoyberg/xml','BSD3','Michael Snoyman <michaels@suite-sol.com>, Aristid Breitkreuz <aristidb@googlemail.com>',750, True, True, False, False),
    (189, 'yesod-paginator','http://github.com/pbrisbin/yesod-paginator','BSD3','Patrick Brisbin',754, False, True, False, False),
    (190, 'esqueleto','https://github.com/meteficha/esqueleto','BSD3','Felipe Lessa',758, True, True, False, False),
    (191, 'idris','http://www.cs.st-andrews.ac.uk/~eb/Idris/','BSD3','Edwin Brady',762, True, True, False, False),
    (192, 'pdf-slave','https://github.com/NCrashed/pdf-slave#readme','BSD3','Anton Gushcha',766, True, True, False, False),
    (193, 'ply-loader','','BSD3','Anthony Cowley',770, True, True, False, False),
    (194, 'qr-imager','https://github.com/vmchale/QRImager#readme','BSD3','Vanessa McHale',774, False, True, False, False),
    (195, 'tagsoup','http://community.haskell.org/~ndm/tagsoup/','BSD3','Neil Mitchell <ndmitchell@gmail.com>',778, True, True, False, False),
    (196, 'ixmonad','','BSD3','Dominic Orchard',782, True, True, False, False),
    (197, 'scalpel','https://github.com/fimad/scalpel','Apache','Will Coster',786, True, False, False, False),
    (198, 'enumerator','http://ianen.org/haskell/enumerator/','MIT','John Millikin <jmillikin@gmail.com>',790, True, True, False, False),
    (199, 'hslogger','http://software.complete.org/hslogger','LGPL','John Goerzen',794, True, True, False, False);